[package]
name = "inc_dec"
version = "0.2.0-beta"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Incrementation and decrementation in Rust."
repository = "https://github.com/coruscateor/inc_dec"
homepage = "https://coruscateor.com/projects/inc-dec"
keywords = ["increment", "decrement", "integer", "extension", "method"]
authors = ["Paul Saunders"]

[dependencies]

[features]
num = []
#no_std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

